/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiRagStreamRouteImport } from './routes/api.rag.stream'
import { Route as ApiVoiceTokenRouteImport } from './routes/api.voice.token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRagStreamRoute = ApiRagStreamRouteImport.update({
  id: '/api/rag/stream',
  path: '/api/rag/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVoiceTokenRoute = ApiVoiceTokenRouteImport.update({
  id: '/api/voice/token',
  path: '/api/voice/token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/rag/stream': typeof ApiRagStreamRoute
  '/api/voice/token': typeof ApiVoiceTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/rag/stream': typeof ApiRagStreamRoute
  '/api/voice/token': typeof ApiVoiceTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/rag/stream': typeof ApiRagStreamRoute
  '/api/voice/token': typeof ApiVoiceTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/rag/stream' | '/api/voice/token'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/rag/stream' | '/api/voice/token'
  id: '__root__' | '/' | '/api/rag/stream' | '/api/voice/token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiRagStreamRoute: typeof ApiRagStreamRoute
  ApiVoiceTokenRoute: typeof ApiVoiceTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rag/stream': {
      id: '/api/rag/stream'
      path: '/api/rag/stream'
      fullPath: '/api/rag/stream'
      preLoaderRoute: typeof ApiRagStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/voice/token': {
      id: '/api/voice/token'
      path: '/api/voice/token'
      fullPath: '/api/voice/token'
      preLoaderRoute: typeof ApiVoiceTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiRagStreamRoute: ApiRagStreamRoute,
  ApiVoiceTokenRoute: ApiVoiceTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
